from __future__ import annotations

from pathlib import Path

import git

from config import config
from github_api.issue_reader import IssueContext
from utils.logger import get_logger

logger = get_logger(__name__)

GIT_AUTHOR_NAME = "AI Issue Fixer"
GIT_AUTHOR_EMAIL = "ai-fixer@users.noreply.github.com"


class CommitError(Exception):
    pass


def commit_and_push(
    repo_path: Path,
    branch: str,
    issue: IssueContext,
    summary: str,
    dry_run: bool = False,
    push_to: str | None = None,
) -> None:
    """
    push_to: repo full name to push to (defaults to issue.repo_full_name).
             Pass the fork's full name when working on a repo without push access.
    """
    repo = git.Repo(repo_path)

    if repo.active_branch.name != branch:
        raise CommitError(
            f"Branch mismatch: expected {branch}, got {repo.active_branch.name}"
        )

    repo.git.add("-A")

    # Abort if nothing changed
    if not repo.index.diff("HEAD") and not repo.untracked_files:
        raise CommitError("No changes to commit — agent made no file modifications")

    commit_msg = (
        f"fix: resolve issue #{issue.number}\n\n"
        f"{summary}\n\n"
        f"Closes #{issue.number}\n"
        f"Generated by AI Issue Fixer Agent"
    )

    author = git.Actor(GIT_AUTHOR_NAME, GIT_AUTHOR_EMAIL)
    repo.index.commit(commit_msg, author=author, committer=author)
    logger.info({"action": "committed", "branch": branch})

    if dry_run:
        logger.info({"action": "dry_run_skip_push"})
        return

    # Embed token in remote URL for push, then clear it
    target_repo = push_to or issue.repo_full_name
    remote_url = f"https://x-access-token:{config.github_token}@github.com/{target_repo}.git"
    origin = repo.remotes["origin"]
    origin.set_url(remote_url)
    try:
        origin.push(refspec=f"{branch}:{branch}")
        logger.info({"action": "pushed", "branch": branch, "to": target_repo})
    finally:
        origin.set_url(f"https://github.com/{target_repo}.git")
