from __future__ import annotations

from github_api.client import get_github_client
from github_api.issue_reader import IssueContext
from config import config
from utils.logger import get_logger

logger = get_logger(__name__)

PR_BODY_TEMPLATE = """\
## Automated Fix for Issue #{issue_number}

**Issue**: {issue_title}
**Branch**: `{branch}`

---

## What Changed

{summary}

---

## Review Checklist

> **This PR was generated by an AI agent and REQUIRES human review before merging.**

- [ ] The fix correctly addresses the reported issue
- [ ] No unintended side effects or regressions introduced
- [ ] Code style and conventions are maintained
- [ ] Tests pass (if applicable)
- [ ] Security implications have been considered

---

Closes #{issue_number}
"""


def create_pull_request(
    issue: IssueContext,
    branch: str,
    summary: str,
    fork_full_name: str | None = None,
) -> str:
    gh = get_github_client()
    # PR is always created on the upstream (original) repo
    repo = gh.get_repo(issue.repo_full_name)

    body = PR_BODY_TEMPLATE.format(
        issue_number=issue.number,
        issue_title=issue.title,
        branch=branch,
        summary=summary,
    )

    # For cross-fork PRs GitHub requires head as "fork_owner:branch"
    if fork_full_name:
        fork_owner = fork_full_name.split("/")[0]
        head = f"{fork_owner}:{branch}"
    else:
        head = branch

    pr = repo.create_pull(
        title=f"fix: {issue.title} (closes #{issue.number})",
        body=body,
        head=head,
        base=config.base_branch,
        draft=False,
        maintainer_can_modify=True,
    )
    # NOTE: pr.enable_automerge() is intentionally never called

    if config.required_reviewers:
        pr.create_review_request(reviewers=config.required_reviewers)
        logger.info({"action": "reviewers_requested", "reviewers": config.required_reviewers})

    # Post a comment on the original issue linking the PR
    issue_obj = repo.get_issue(issue.number)
    issue_obj.create_comment(
        f"An automated fix has been proposed in PR #{pr.number}: {pr.html_url}\n\n"
        f"A human must review and approve before this can be merged."
    )

    logger.info({"action": "pr_created", "pr_number": pr.number, "url": pr.html_url})
    return pr.html_url
